#!/bin/bash
. /etc/sysconfig/cranix

if [ ${CRANIX_RESET_REGISTER_PASSWORD} = "no" ]
then
    exit 0;
fi

TOKEN=$( mktemp -u XXXXXXXXXXXX )
/usr/bin/samba-tool domain passwordsettings set --complexity=off
/usr/bin/samba-tool user setpassword register --newpassword=$TOKEN
if [ $? = 0 ]
then
	sed -i s/de.cranix.dao.User.Register.Password=.*/de.cranix.dao.User.Register.Password=$TOKEN/ /opt/cranix-java/conf/cranix-api.properties
fi
if [ $CRANIX_CHECK_PASSWORD_QUALITY = "yes" ]
then
    /usr/bin/samba-tool domain passwordsettings set --complexity=on
fi
/usr/bin/systemctl restart cranix-api
sleep 30
/usr/sbin/crx_api.sh PUT softwares/saveState

