#!/bin/bash
#
# Copyright (c) 2017 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.
#

PACKAGES=$@


while [ -e /var/run/zypp.pid ]
do
  ZPID=( cat /var/run/zypp.pid )
  if [ -z "$ZPID" -o ! -e /proc/$ZPID ]
  then
     rm -f /var/run/zypp.pid
  else
     sleep 2
  fi
done

/usr/bin/zypper -nD /srv/salt/repos.d/ install -r salt-packages $PACKAGES

