#!/bin/bash
export HOME="/root"
while( test -e /run/lock/get_next_id )
do
	sleep 1
done
touch /run/lock/get_next_id
echo "INSERT INTO OssNextID Values(NULL);" | mysql OSS
echo "SELECT MAX(id) FROM OssNextID" | mysql OSS | tail -n 1
rm -f /run/lock/get_next_id
